import { createCase, deleteCase, isFirebaseConfigured, loadCases } from './firebase-data.js';
const $ = selector => document.querySelector(selector); let cases = []; let remote = false;
function toast(message) { const node = $('#admin-toast'); node.textContent = message; node.classList.remove('hidden'); clearTimeout(window.adminToast); window.adminToast = setTimeout(() => node.classList.add('hidden'), 2600); }
function statusClass(status) { return status === '已完成' ? 'done' : status === '待補件' ? 'pending' : 'review'; }
function renderCases() { const query = ($('#admin-search').value || '').toLowerCase(); const filter = $('#admin-status').value; const visible = cases.filter(item => (filter === 'all' || item.status === filter) && `${item.id} ${item.name} ${item.org}`.toLowerCase().includes(query)); $('#admin-empty').classList.toggle('hidden', visible.length > 0); $('#admin-case-table').innerHTML = visible.map(item => `<tr><td><div class="case-name"><strong>${item.name}</strong><small>${item.id}</small></div></td><td>${item.org}</td><td>${item.reviewer || '待指派'}</td><td>${item.due || '—'}</td><td><span class="status ${statusClass(item.status)}">${item.status}</span></td><td><button class="table-action" data-delete="${item.id}">刪除</button></td></tr>`).join(''); }
async function init() { $('#connection-status').textContent = isFirebaseConfigured ? 'Firebase 已設定' : '離線模式'; try { const remoteCases = await loadCases(); if (remoteCases) { cases = remoteCases; remote = true; $('#connection-status').textContent = 'Firestore 已連線'; } } catch (error) { console.error(error); $('#connection-status').textContent = 'Firestore 連線失敗'; } if (!cases.length) cases = JSON.parse(localStorage.getItem('review-cases') || '[]'); renderCases(); }
function openModal() { $('#admin-modal').classList.remove('hidden'); const date = new Date(); date.setDate(date.getDate() + 14); $('#admin-case-form [name=due]').value = date.toISOString().slice(0, 10); } function closeModal() { $('#admin-modal').classList.add('hidden'); }
document.querySelectorAll('.admin-nav-item').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('.admin-nav-item').forEach(item => item.classList.remove('active')); document.querySelectorAll('.admin-section').forEach(section => section.classList.remove('active')); button.classList.add('active'); $(`#admin-${button.dataset.section}`).classList.add('active'); }));
$('#admin-search').addEventListener('input', renderCases); $('#admin-status').addEventListener('change', renderCases); $('#admin-new-case').addEventListener('click', openModal); $('#admin-close').addEventListener('click', closeModal); $('#admin-cancel').addEventListener('click', closeModal);
$('#admin-case-form').addEventListener('submit', async event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.target)); try { const saved = remote ? await createCase(data) : { id: `EDU-${Date.now()}`, ...data, status: '審查中', updated: '剛剛' }; cases.unshift({ ...saved, status: saved.status || '審查中' }); localStorage.setItem('review-cases', JSON.stringify(cases)); renderCases(); closeModal(); event.target.reset(); toast(remote ? '案件已儲存至 Firestore' : '案件已儲存於本機'); } catch (error) { console.error(error); toast('儲存失敗，請檢查 Firebase 設定'); } });
document.addEventListener('click', async event => { const button = event.target.closest('[data-delete]'); if (button) { const id = button.dataset.delete; if (!confirm('確定要刪除此案件？')) return; try { if (remote) await deleteCase(id); cases = cases.filter(item => item.id !== id); localStorage.setItem('review-cases', JSON.stringify(cases)); renderCases(); toast('案件已刪除'); } catch (error) { console.error(error); toast('刪除失敗'); } } const coming = event.target.closest('[data-coming]'); if (coming) toast(coming.dataset.coming); }); $('#save-settings').addEventListener('click', () => toast('設定介面已準備，正式儲存將寫入 settings 集合')); init();
