import { createCase, deleteCase, getCurrentUser, getUserRole, isFirebaseConfigured, loadCases, loadDocuments, signInWithGoogle, signOutUser, updateUserRole } from './firebase-data.js';

const $ = selector => document.querySelector(selector);
let cases = [], remote = false, currentRole = 'viewer';
const roleNames = { admin: '管理員', editor: '編輯者', viewer: '檢視者' };
function toast(message) { const node = $('#admin-toast'); node.textContent = message; node.classList.remove('hidden'); clearTimeout(window.adminToast); window.adminToast = setTimeout(() => node.classList.add('hidden'), 2600); }
function statusClass(status) { return status === '已完成' ? 'done' : status === '待補件' ? 'pending' : 'review'; }
function renderCases() { const query = ($('#admin-search').value || '').toLowerCase(), filter = $('#admin-status').value; const visible = cases.filter(item => (filter === 'all' || item.status === filter) && `${item.id} ${item.name} ${item.org}`.toLowerCase().includes(query)); $('#admin-empty').classList.toggle('hidden', visible.length > 0); $('#admin-case-table').innerHTML = visible.map(item => `<tr><td><div class="case-name"><strong>${item.name || '未命名案件'}</strong><small>${item.id}</small></div></td><td>${item.org || '—'}</td><td>${item.reviewer || '待指派'}</td><td>${item.due || '—'}</td><td><span class="status ${statusClass(item.status)}">${item.status || '審查中'}</span></td><td>${currentRole === 'admin' ? `<button class="table-action" data-delete="${item.id}">刪除</button>` : '—'}</td></tr>`).join(''); }
function applyRole() { $('#admin-user-role').textContent = roleNames[currentRole] || roleNames.viewer; document.querySelectorAll('.admin-only').forEach(el => el.classList.toggle('hidden', currentRole !== 'admin')); $('#admin-new-case').classList.toggle('hidden', currentRole === 'viewer'); $('#save-settings').disabled = currentRole !== 'admin'; }
async function renderUsers() { const users = await loadDocuments('users') || []; $('#admin-user-table').innerHTML = users.map(user => `<tr><td><strong>${user.displayName || '未命名使用者'}</strong></td><td>${user.email || '—'}</td><td><span class="role-badge">${roleNames[user.role] || roleNames.viewer}</span></td><td><select class="user-role-select" data-user-role="${user.id}" ${user.id === $('#admin-avatar').dataset.uid ? 'disabled' : ''}><option value="viewer" ${user.role === 'viewer' ? 'selected' : ''}>檢視者</option><option value="editor" ${user.role === 'editor' ? 'selected' : ''}>編輯者</option><option value="admin" ${user.role === 'admin' ? 'selected' : ''}>管理員</option></select></td></tr>`).join(''); }
async function enterApp(user) { currentRole = await getUserRole(user.uid); $('#admin-app').classList.remove('hidden'); $('#admin-login-gate').classList.add('hidden'); $('#admin-display-name').textContent = user.displayName || user.email || '使用者'; $('#admin-avatar').textContent = (user.displayName || user.email || '使').slice(0, 1); $('#admin-avatar').dataset.uid = user.uid; applyRole(); try { const remoteCases = await loadCases(); if (remoteCases) { cases = remoteCases; remote = true; $('#connection-status').textContent = 'Firestore 已連線'; } } catch (error) { console.error(error); $('#connection-status').textContent = 'Firestore 連線失敗'; toast('目前帳號沒有讀取資料的權限'); } if (!cases.length) cases = JSON.parse(localStorage.getItem('review-cases') || '[]'); renderCases(); }
async function init() { $('#connection-status').textContent = isFirebaseConfigured ? 'Firebase 已設定' : '離線模式'; const user = await getCurrentUser(); if (user) await enterApp(user); }
function openModal() { if (currentRole === 'viewer') return toast('檢視者沒有新增權限'); $('#admin-modal').classList.remove('hidden'); const date = new Date(); date.setDate(date.getDate() + 14); $('#admin-case-form [name=due]').value = date.toISOString().slice(0, 10); }
function closeModal() { $('#admin-modal').classList.add('hidden'); }
document.querySelectorAll('.admin-nav-item').forEach(button => button.addEventListener('click', async () => { if (button.classList.contains('hidden')) return; document.querySelectorAll('.admin-nav-item').forEach(item => item.classList.remove('active')); document.querySelectorAll('.admin-section').forEach(section => section.classList.remove('active')); button.classList.add('active'); $(`#admin-${button.dataset.section}`).classList.add('active'); if (button.dataset.section === 'users') await renderUsers(); }));
$('#admin-search').addEventListener('input', renderCases); $('#admin-status').addEventListener('change', renderCases); $('#admin-new-case').addEventListener('click', openModal); $('#admin-close').addEventListener('click', closeModal); $('#admin-cancel').addEventListener('click', closeModal);
$('#admin-google-login').addEventListener('click', async () => { const button = $('#admin-google-login'); button.disabled = true; button.textContent = '登入中…'; try { const result = await signInWithGoogle(); await enterApp(result.user); } catch (error) { console.error(error); $('#admin-login-error').textContent = error.message || 'Google 登入失敗，請確認 Firebase 已啟用 Google 提供者。'; $('#admin-login-error').classList.remove('hidden'); button.disabled = false; button.textContent = '使用 Google 登入'; } });
$('#admin-signout').addEventListener('click', async () => { await signOutUser(); location.reload(); });
$('#admin-case-form').addEventListener('submit', async event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.target)); try { const saved = remote ? await createCase(data) : { id: `EDU-${Date.now()}`, ...data, status: '審查中', updated: '剛剛' }; cases.unshift({ ...saved, status: saved.status || '審查中' }); localStorage.setItem('review-cases', JSON.stringify(cases)); renderCases(); closeModal(); event.target.reset(); toast(remote ? '案件已儲存至 Firestore' : '案件已儲存於本機'); } catch (error) { console.error(error); toast('儲存失敗，請檢查權限'); } });
document.addEventListener('click', async event => { const button = event.target.closest('[data-delete]'); if (button) { if (currentRole !== 'admin') return toast('只有管理員可以刪除案件'); const id = button.dataset.delete; if (!confirm('確定要刪除此案件？')) return; try { if (remote) await deleteCase(id); cases = cases.filter(item => item.id !== id); localStorage.setItem('review-cases', JSON.stringify(cases)); renderCases(); toast('案件已刪除'); } catch (error) { console.error(error); toast('刪除失敗，請檢查權限'); } } const coming = event.target.closest('[data-coming]'); if (coming) toast(coming.dataset.coming); });
document.addEventListener('change', async event => { const select = event.target.closest('[data-user-role]'); if (!select || currentRole !== 'admin') return; try { await updateUserRole(select.dataset.userRole, select.value); toast('使用者權限已更新'); await renderUsers(); } catch (error) { console.error(error); toast('權限更新失敗'); } });
init();
